Repository dsccommunity/xDhcpServer, pull requests merged in 2018-06, with the labels that each got.

#42 Added Router to resource description in Readme
  README.md
Labels: needs review

#44 xDhcpServer: Added default AppVeyor template and status badges
  .codecov.yml
  LICENSE
  README.md
  appveyor.yml
  xDhcpServer.psd1
Labels: needs review

#47 Activate the GitHub App Stale on the GitHub repository
  .github/stale.yml
Labels: needs review

#43 Resources for managing DHCP option values (server, scope, reserved IP and policy)
  DSCResources/MSFT_DhcpPolicyOptionValue/MSFT_DhcpPolicyOptionValue.psm1
  DSCResources/MSFT_DhcpPolicyOptionValue/MSFT_DhcpPolicyOptionValue.schema.mof
  DSCResources/MSFT_DhcpReservedIPOptionValue/MSFT_DhcpReservedIPOptionValue.psm1
  DSCResources/MSFT_DhcpReservedIPOptionValue/MSFT_DhcpReservedIPOptionValue.schema.mof
  DSCResources/MSFT_DhcpScopeOptionValue/MSFT_DhcpScopeOptionValue.psm1
  DSCResources/MSFT_DhcpScopeOptionValue/MSFT_DhcpScopeOptionValue.schema.mof
  DSCResources/MSFT_DhcpServerOptionValue/MSFT_DhcpServerOptionValue.psm1
  DSCResources/MSFT_DhcpServerOptionValue/MSFT_DhcpServerOptionValue.schema.mof
  Modules/CommonResourceHelper.psm1
  Modules/DhcpServerDsc.OptionValueHelper/OptionValueHelper.psm1
  Modules/DhcpServerDsc.OptionValueHelper/en-US/OptionValueHelper.strings.psd1
  README.md
  Samples/DhcpPolicyOptionValue/DhcpPolicyOptionValue.ps1
  Samples/DhcpReservedIPOptionValue/DhcpReservedIPOptionValue.ps1
  Samples/DhcpScopeOptionValue/DhcpScopeOptionValue.ps1
  Samples/DhcpServerOptionValue/DhcpServerOptionValue.ps1
  Tests/Unit/CommonResourceHelper.Tests.ps1
  Tests/Unit/MSFT_DhcpPolicyOptionValue.Tests.ps1
  Tests/Unit/MSFT_DhcpReservedIPOptionValue.Tests.ps1
  Tests/Unit/MSFT_DhcpScopeOptionValue.Tests.ps1
  Tests/Unit/MSFT_DhcpServerOptionValue.Tests.ps1
Labels: waiting for code fix

#49 BREAKING CHANGE: Used ScopeId as a key property for xDhcpServerScope resource.
  DSCResources/Helper.psm1
  DSCResources/MSFT_xDhcpServerClass/MSFT_xDhcpServerClass.psm1
  DSCResources/MSFT_xDhcpServerScope/MSFT_xDhcpServerScope.psm1
  DSCResources/MSFT_xDhcpServerScope/MSFT_xDhcpServerScope.schema.mof
  README.md
  Tests/Unit/Helper.Tests.ps1
  Tests/Unit/MSFT_xDhcpServerScope.Tests.ps1
Labels: breaking change, needs review
